# Generated by Django 5.2.2 on 2026-07-22 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Employee Engagement', 'Employee Engagement'), ('Operations', 'Operations'), ('HR', 'HR'), ('Safety', 'Safety'), ('Training', 'Training'), ('Events', 'Events'), ('General', 'General')], default='General', max_length=100)),
                ('poll_type', models.CharField(choices=[('Single Choice', 'Single Choice'), ('Multiple Choice', 'Multiple Choice'), ('Rating Scale (1-5)', 'Rating Scale (1-5)'), ('Yes/No', 'Yes/No'), ('Open Text', 'Open Text'), ('Emoji Reaction', 'Emoji Reaction')], default='Single Choice', max_length=50)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('anonymous', models.BooleanField(default=False)),
                ('allow_multiple_responses', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
            options={
                'db_table': 'poll_details',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple-choice', 'Single Choice'), ('checkbox', 'Multiple Choice'), ('rating', 'Rating Scale (1-5)'), ('yes-no', 'Yes/No'), ('text', 'Open Text'), ('emoji', 'Emoji Reaction')], default='multiple-choice', max_length=50)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll.poll')),
            ],
            options={
                'db_table': 'poll_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_value', models.IntegerField(blank=True, null=True)),
                ('answer_options', models.JSONField(blank=True, default=list)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='poll.poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='poll.pollquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poll_responses',
                'ordering': ['-submitted_on'],
            },
        ),
        migrations.CreateModel(
            name='PollShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('submitted', 'Submitted')], default='sent', max_length=50)),
                ('sent_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='poll.poll')),
                ('sent_to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_shares_group', to='user.groups')),
                ('sent_to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_shares_location', to='user.locations')),
                ('sent_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poll_shares',
            },
        ),
    ]
