"""
Django settings for vibro project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
from datetime import timedelta
import boto3

from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-rz@0!ryajts-!ew+pq^3)k1u&mrsjf%g!+yjx2s&&=^1f3=y5#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',') if os.getenv('ALLOWED_HOSTS') else ["*"]

FORCE_HTTPS = os.getenv("FORCE_HTTPS", "false").lower() in ("true", "1", "yes")

APPEND_SLASH= False


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',
    'user',
    'form',
    'task',
    'announcement',
    'django_filters',
    'draft',
    'learning',
    'planner',
    'poll',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'vibro.archived_org_middleware.ArchivedOrganizationMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "http://192.168.29.220:8000",
    "http://192.168.1.10:8000",
    "http://192.168.1.21:8000",
    "http://192.168.1.6:8000",
    "http://192.168.1.10:8000",
    "http://192.168.1.4:8000",
    "http://192.168.1.3:8000",
    "https://vibro.onrender.com",
    "https://vibro-prod-v01.vercel.app",
    "https://vibro-dev-v01.netlify.app",
    "http://43.205.114.131:3000",
    "http://15.207.100.5:3000",
    "http://13.201.21.27:3000",
    "http://3.111.33.92:3000",
    "http://192.168.1.11:3000",
    "http://10.134.35.13:3000",
    "http://3.214.129.187:3000",
    "http://13.235.52.239:3000",
    "http://54.198.22.28:3000",
    "http://www.vibroets.com:3000",
    "https://www.vibroets.com:3000",
    "http://www.vibroets.com",
    "https://www.vibroets.com",
    "http://vibroets.com",
    "https://vibroets.com",
    "https://vibro-qa.vercel.app",
    "http://localhost:8081",
    "http://localhost:8082",
    "http://127.0.0.1:8081",
    "http://127.0.0.1:8082",
]
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = ['authorization', 'content-type']

ROOT_URLCONF = 'vibro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vibro.wsgi.application'
ASGI_APPLICATION = 'vibro.asgi.application'

REDIS_HOST = os.getenv("REDIS_HOST")
if REDIS_HOST:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(REDIS_HOST, int(os.getenv("REDIS_PORT", "6379")))],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.sqlite3")
if DB_ENGINE == "django.db.backends.postgresql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME", "vibro"),
            'USER': os.getenv("DB_USER", "vibro"),
            'PASSWORD': os.getenv("DB_PASSWORD", "vibro_pass_2024"),
            'HOST': os.getenv("DB_HOST", "db"),
            'PORT': os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=8),
    'AUTH_HEADER_TYPES': ('Bearer',),
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.CustomUser'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtpout.secureserver.net'  # GoDaddy SMTP server
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'support@vibroets.com'
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'Vb@123456')
# EMAIL_FROM_ADDRESS = 'support@vibroets.com'
# DEFAULT_FROM_EMAIL = EMAIL_FROM_ADDRESS

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_FROM_ADDRESS = 'vibro.chennai@gmail.com'  # Gmail address
EMAIL_HOST_PASSWORD = 'zpvr fcsz cuec tbtm'     # App Password
EMAIL_HOST_USER = 'vibro.chennai@gmail.com'







# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#S3 BUCKET SETTINGS
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_DEFAULT_REGION = os.getenv("AWS_REGION")
S3_BUCKET_NAME = os.getenv("FORMS_UPLOAD_BUCKET")
S3_BUCKET_NAME_ANNOUNCEMENT = os.getenv("ANNOUNCEMENTS_UPLOAD_BUCKET")
S3_DRAFT_FORMS_BUCKET = os.getenv("FORMS_DRAFT_BUCKET")

# Only initialize S3 client when AWS credentials are configured.
# When running with local storage, these can be left unset.
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION:
    S3_CLIENT = boto3.client(
        "s3",
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        region_name=AWS_DEFAULT_REGION
    )
else:
    S3_CLIENT = None

# File upload settings for announcement attachments
FILE_UPLOAD_MAX_MEMORY_SIZE = 50_000_000  # 50MB (files larger than this go to disk)
DATA_UPLOAD_MAX_MEMORY_SIZE = 50_000_000  # 50MB (form data kept in memory)
DATA_UPLOAD_MAX_NUMBER_FILES = 10  # Max 10 files per announcement
