# Generated by Django 5.2.2 on 2026-07-02 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('audit', 'Audit'), ('table', 'Table'), ('location', 'Location'), ('division', 'Division'), ('sub_division', 'Sub Division'), ('title_and_description', 'Title and Description'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('multiple_choice', 'Multiple Choice'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Dropdown'), ('linear_scale', 'Linear Scale'), ('datetime', 'Datetime'), ('date', 'Date'), ('time', 'Time'), ('signature', 'Signature'), ('upload_image', 'Upload Image'), ('upload_video', 'Upload Video'), ('upload_file', 'Upload File'), ('qr_code', 'QR Code'), ('formula', 'Formula'), ('user', 'User')], max_length=30)),
                ('answer', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('other_text', models.TextField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_stages', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditFormSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_assignment_uuid', models.CharField(max_length=255)),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('form_overall_status', models.CharField(blank=True, help_text='Overall status: PASS/FAIL', max_length=50, null=True)),
                ('form_overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall score percentage', max_digits=10, null=True)),
                ('form_critical_failed', models.IntegerField(default=0, help_text='Number of critical items failed')),
                ('groups_status', models.CharField(blank=True, help_text='Group status: passed/failed', max_length=50, null=True)),
                ('group_score', models.DecimalField(blank=True, decimal_places=2, help_text='Group score percentage', max_digits=10, null=True)),
                ('group_percentage', models.CharField(blank=True, help_text='Group percentage', max_length=50, null=True)),
                ('group_critical_failed', models.IntegerField(default=0, help_text='Number of critical items failed for the group')),
            ],
            options={
                'db_table': 'form_auditformsubmissionhistory',
            },
        ),
        migrations.CreateModel(
            name='AuditGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('group_uuid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuditInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('group_uuid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_days', models.IntegerField(default=7)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTaskCloseQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Answer to the task close question')),
                ('answer_data', models.JSONField(blank=True, help_text='Additional answer data (for file uploads, etc.)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'form_followuptaskclosequestionresponse',
            },
        ),
        migrations.CreateModel(
            name='FollowUpTaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(help_text='Response data for the task (answers summary)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('form_type', models.CharField(choices=[('standard', 'Standard'), ('location', 'Location'), ('audit', 'Audit')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('GPS', models.BooleanField(default=False)),
                ('trigger_email_notifications', models.BooleanField(default=False)),
                ('share_response', models.BooleanField(default=False)),
                ('allow_editing', models.BooleanField(default=False)),
                ('can_edit_previous_state', models.BooleanField(default=False)),
                ('auto_share_response', models.BooleanField(default=False)),
                ('pass_percentage', models.BigIntegerField(blank=True, null=True)),
                ('max_score', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('last_deleted_date', models.DateTimeField(blank=True, null=True)),
                ('last_archived_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'form_master',
            },
        ),
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('leader', 'Location Leader')], max_length=30)),
                ('form_shared_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FormAutoShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'form_auto_share_config',
            },
        ),
        migrations.CreateModel(
            name='FormPayloadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('form_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress')], max_length=30, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('post', 'POST'), ('put', 'PUT'), ('duplicate', 'DUPLICATE')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormResponseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('shared_on', models.DateTimeField(auto_now_add=True)),
                ('share_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('location_leader', 'Location Leader')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSubmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_initiated_on', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_order', models.PositiveIntegerField(default=1)),
                ('assignment_uuid', models.CharField(max_length=255)),
                ('is_assignment_fullfilled', models.BooleanField(default=False)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('logic_type', models.CharField(choices=[('is', 'IS'), ('is_not', 'IS NOT')], max_length=255)),
                ('comparison', models.CharField(blank=True, choices=[('equals', 'Equals'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('greaterthan_or_equalto', 'Greater Than or Equal To'), ('lessthan_or_equalto', 'Less Than or Equal To')], max_length=50, null=True)),
                ('logic_value', models.CharField(max_length=255)),
                ('notification', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LogicFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.BigIntegerField()),
                ('assign_to', models.CharField(choices=[('form_submitter', 'Form Submiiter'), ('user', 'User'), ('group', 'Group'), ('leader', 'Location Leader')], max_length=255)),
                ('assign_user_ids', models.JSONField(blank=True, default=list, help_text='List of user IDs from assignUsers')),
                ('assign_group_ids', models.JSONField(blank=True, default=list, help_text='List of group IDs from assignGroups')),
                ('assign_leader_ids', models.JSONField(blank=True, default=list, help_text='List of leader user IDs from assignLeaders')),
                ('followup_toggle', models.BooleanField(default=False, help_text='Toggle to enable/disable followup for this logic')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('option', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('question_uuid', models.CharField(default='default_uuid', max_length=255)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('critical', models.BooleanField(default=False)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('question_type', models.CharField(choices=[('audit', 'Audit'), ('table', 'Table'), ('location', 'Location'), ('division', 'Division'), ('sub_division', 'Sub Division'), ('title_and_description', 'Title and Description'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('multiple_choice', 'Multiple Choice'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Dropdown'), ('linear_scale', 'Linear Scale'), ('datetime', 'Datetime'), ('date', 'Date'), ('time', 'Time'), ('signature', 'Signature'), ('upload_image', 'Upload Image'), ('upload_video', 'Upload Video'), ('upload_file', 'Upload File'), ('qr_code', 'QR Code'), ('formula', 'Formula'), ('user', 'User')], max_length=30)),
                ('question_sub_type', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number')], max_length=255, null=True)),
                ('question_hint', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
                ('require_live', models.BooleanField(default=False)),
                ('number_of_file_allowed', models.BigIntegerField(blank=True, null=True)),
                ('min_value', models.BigIntegerField(blank=True, null=True)),
                ('max_value', models.BigIntegerField(blank=True, null=True)),
                ('max_score', models.BigIntegerField(blank=True, null=True)),
                ('is_logic_question', models.BooleanField(default=False)),
                ('is_task_close_question', models.BooleanField(default=False)),
                ('is_audit_info_question', models.BooleanField(default=False)),
                ('is_other', models.BooleanField(default=False)),
                ('reference_images', models.JSONField(blank=True, default=list, null=True)),
                ('reference_videos', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('stage_uuid', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('user', 'Specific User'), ('group', 'Specific Group'), ('previous_stage', 'Previous Stage'), ('organization', 'Anyone in the Organization')], max_length=255)),
                ('allow_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('stage_approvals', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('assignment_uuid', models.CharField(max_length=255)),
                ('is_assignment_fullfilled', models.BooleanField(default=False)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('stage_assignment_uuid', models.CharField(max_length=255)),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCloseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'form_taskclosequestion',
            },
        ),
    ]
