# Generated by Django 5.2.2 on 2026-07-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        ('task', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_division', to='user.divisions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='user.locations'),
        ),
        migrations.AddField(
            model_name='answer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='user.organization'),
        ),
        migrations.AddField(
            model_name='answer',
            name='sub_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_subdivision', to='user.divisions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditformsubmissionhistory',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_group_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditformsubmissionhistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_submissions_history', to='user.organization'),
        ),
        migrations.AddField(
            model_name='auditgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='auditgroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditformsubmissionhistory',
            name='group_id',
            field=models.ForeignKey(blank=True, help_text='Reference to the audit group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_submission_histories', to='form.auditgroup'),
        ),
        migrations.AddField(
            model_name='auditinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditinfo',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='auditinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='form.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups assigned to complete this follow-up', related_name='group_assigned_followup_tasks', to='user.groups'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='assigned_location_leaders',
            field=models.ManyToManyField(blank=True, help_text='Location leaders assigned to complete this follow-up', related_name='leader_assigned_followup_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to complete this follow-up', related_name='assigned_followup_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who completed this follow-up task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_followup_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='parent_followup',
            field=models.ForeignKey(blank=True, help_text='Parent follow-up task if this is a nested follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_followups', to='form.followuptask'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='reopened_by',
            field=models.ForeignKey(blank=True, help_text='User who last reopened this follow-up task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_followup_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='started_by',
            field=models.ForeignKey(blank=True, help_text='User who started working on this follow-up task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_followup_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='task_details',
            field=models.ForeignKey(blank=True, help_text='Corresponding entry in task_details table', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_task', to='task.task'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptaskclosequestionresponse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_close_question_responses', to='user.organization'),
        ),
        migrations.AddField(
            model_name='followuptaskclosequestionresponse',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_close_question_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptaskclosequestionresponse',
            name='task',
            field=models.ForeignKey(help_text='The follow-up task this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='task_close_question_responses', to='form.followuptask'),
        ),
        migrations.AddField(
            model_name='followuptaskresponse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_task_responses', to='user.organization'),
        ),
        migrations.AddField(
            model_name='followuptaskresponse',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptaskresponse',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='form.followuptask'),
        ),
        migrations.AddField(
            model_name='form',
            name='archivedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='deletedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.folder'),
        ),
        migrations.AddField(
            model_name='form',
            name='form_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='form',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='assigned_form',
            field=models.ForeignKey(blank=True, help_text='The form that needs to be filled as follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_assigned_tasks', to='form.form'),
        ),
        migrations.AddField(
            model_name='auditinfo',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_info', to='form.form'),
        ),
        migrations.AddField(
            model_name='auditgroup',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_group', to='form.form'),
        ),
        migrations.AddField(
            model_name='auditformsubmissionhistory',
            name='form_id',
            field=models.ForeignKey(blank=True, help_text='Reference to the form', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_submission_histories', to='form.form'),
        ),
        migrations.AddField(
            model_name='answer',
            name='Form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.form'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='form.form'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_forms', to='user.groups'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_assigned_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assigned_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formautoshareconfig',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_share_config', to='form.form'),
        ),
        migrations.AddField(
            model_name='formautoshareconfig',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='auto_shared_forms', to='user.groups'),
        ),
        migrations.AddField(
            model_name='formautoshareconfig',
            name='location_leaders',
            field=models.ManyToManyField(blank=True, related_name='auto_shared_leader_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formautoshareconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
        migrations.AddField(
            model_name='formautoshareconfig',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='auto_shared_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formpayloadfiles',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payload_files', to='form.form'),
        ),
        migrations.AddField(
            model_name='formpayloadfiles',
            name='form_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payload_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formpayloadfiles',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload_files', to='user.organization'),
        ),
        migrations.AddField(
            model_name='formresponseshare',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponseshare',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='formresponseshare',
            name='shared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponseshare',
            name='shared_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_responses_groups', to='user.groups'),
        ),
        migrations.AddField(
            model_name='formresponseshare',
            name='shared_to_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_responses_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponseshare',
            name='shared_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponseshare',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmision',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmision',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.form'),
        ),
        migrations.AddField(
            model_name='formsubmision',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='user.organization'),
        ),
        migrations.AddField(
            model_name='formsubmision',
            name='submission_initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponseshare',
            name='form_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='followuptaskresponse',
            name='form_submission',
            field=models.ForeignKey(blank=True, help_text='The actual form submission for this follow-up task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_task_responses', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='followup_submission',
            field=models.ForeignKey(blank=True, help_text='The submission created for this follow-up form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_source_task', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='main_form_submission',
            field=models.ForeignKey(blank=True, help_text='The main form submission that triggered this follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='auditformsubmissionhistory',
            name='form_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_submissions_history', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_groups_to_another_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignment', to='form.form'),
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_assignment', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignment', to='form.auditgroup'),
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignment', to='user.organization'),
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logic',
            name='audit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.auditgroup'),
        ),
        migrations.AddField(
            model_name='logic',
            name='audit_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.auditinfo'),
        ),
        migrations.AddField(
            model_name='logic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logic',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='logic',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.groups'),
        ),
        migrations.AddField(
            model_name='logic',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='logic',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='logic',
            field=models.ForeignKey(blank=True, help_text='Logic that triggered this follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='form.logic'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='assign_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_form', to='form.form'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='audit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.auditgroup'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='audit_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.auditinfo'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.groups'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logic_followup_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='logic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='form.logic'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='audit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='form.auditgroup'),
        ),
        migrations.AddField(
            model_name='option',
            name='audit_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='form.auditinfo'),
        ),
        migrations.AddField(
            model_name='option',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='form.form'),
        ),
        migrations.AddField(
            model_name='option',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='option',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='audit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.auditgroup'),
        ),
        migrations.AddField(
            model_name='question',
            name='audit_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.auditinfo'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='form.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='form.question'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_parent_question', to='form.question'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='task_close_questions',
            field=models.ManyToManyField(related_name='follow_up_task_close_child_questions', to='form.question'),
        ),
        migrations.AddField(
            model_name='logic',
            name='logic_questions',
            field=models.ManyToManyField(related_name='logic_child_questions', to='form.question'),
        ),
        migrations.AddField(
            model_name='logic',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_parent_question', to='form.question'),
        ),
        migrations.AddField(
            model_name='followuptaskclosequestionresponse',
            name='question',
            field=models.ForeignKey(help_text='The task close question', on_delete=django.db.models.deletion.CASCADE, related_name='task_close_responses', to='form.question'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='main_form_question',
            field=models.ForeignKey(blank=True, help_text='Question that triggered this follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_followups', to='form.question'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='task_close_questions',
            field=models.ManyToManyField(blank=True, help_text='Questions to ask when reopening the task', related_name='followup_task_close_questions', to='form.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.question'),
        ),
        migrations.AddField(
            model_name='stage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='form.form'),
        ),
        migrations.AddField(
            model_name='stage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organization', to='user.organization'),
        ),
        migrations.AddField(
            model_name='stage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.stage'),
        ),
        migrations.AddField(
            model_name='option',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='form.stage'),
        ),
        migrations.AddField(
            model_name='logicfollowup',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.stage'),
        ),
        migrations.AddField(
            model_name='logic',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.stage'),
        ),
        migrations.AddField(
            model_name='formsubmision',
            name='submission_initiated_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.stage'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='main_form_stage',
            field=models.ForeignKey(blank=True, help_text='Stage that triggered this follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_followups', to='form.stage'),
        ),
        migrations.AddField(
            model_name='answer',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.stage'),
        ),
        migrations.AddField(
            model_name='stageaccess',
            name='allow_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.groups'),
        ),
        migrations.AddField(
            model_name='stageaccess',
            name='allow_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stageaccess',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='stageaccess',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_parent_stage', to='form.stage'),
        ),
        migrations.AddField(
            model_name='stageassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages_to_another_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stageassignment',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to='form.form'),
        ),
        migrations.AddField(
            model_name='stageassignment',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='stageassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to='user.organization'),
        ),
        migrations.AddField(
            model_name='stageassignment',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to='form.stage'),
        ),
        migrations.AddField(
            model_name='stageassignment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to='task.task'),
        ),
        migrations.AddField(
            model_name='stageassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagesubmissionhistory',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stage_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagesubmissionhistory',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_stage_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagesubmissionhistory',
            name='form_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_submissions_history', to='form.formsubmision'),
        ),
        migrations.AddField(
            model_name='stagesubmissionhistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_submissions_history', to='user.organization'),
        ),
        migrations.AddField(
            model_name='stagesubmissionhistory',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_submissions_history', to='form.stage'),
        ),
        migrations.AddField(
            model_name='taskclosequestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_close_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskclosequestion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_close_assignments', to='user.organization'),
        ),
        migrations.AddField(
            model_name='taskclosequestion',
            name='question',
            field=models.ForeignKey(help_text='The task close question', on_delete=django.db.models.deletion.CASCADE, related_name='task_close_assignments', to='form.question'),
        ),
        migrations.AddField(
            model_name='taskclosequestion',
            name='task',
            field=models.ForeignKey(help_text='The follow-up task this question is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='task_close_questions_link', to='task.task'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'organization', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='auditinfo',
            unique_together={('form', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='auditgroup',
            unique_together={('form', 'name')},
        ),
        migrations.AddIndex(
            model_name='auditformsubmissionhistory',
            index=models.Index(fields=['form_submission'], name='form_auditf_form_su_dedbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditformsubmissionhistory',
            index=models.Index(fields=['form_id'], name='form_auditf_form_id_287ada_idx'),
        ),
        migrations.AddIndex(
            model_name='auditformsubmissionhistory',
            index=models.Index(fields=['group_id'], name='form_auditf_group_i_4c56d9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditformsubmissionhistory',
            index=models.Index(fields=['organization'], name='form_auditf_organiz_7e0317_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptaskclosequestionresponse',
            index=models.Index(fields=['task', 'question'], name='form_follow_task_id_82bbc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followuptaskclosequestionresponse',
            unique_together={('task', 'question')},
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['form'], name='form_stage_form_id_30cc51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('form', 'stage_uuid', 'name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['form'], name='form_questi_form_id_3615ec_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['stage'], name='form_questi_stage_i_121627_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['parent_question'], name='form_questi_parent__ab4526_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('form', 'stage', 'question_uuid', 'question_type', 'organization')},
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['form'], name='form_option_form_id_3d7b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['stage'], name='form_option_stage_i_ea6e87_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question'], name='form_option_questio_74e141_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'option')},
        ),
        migrations.AddIndex(
            model_name='logicfollowup',
            index=models.Index(fields=['form'], name='form_logicf_form_id_a54de0_idx'),
        ),
        migrations.AddIndex(
            model_name='logicfollowup',
            index=models.Index(fields=['stage'], name='form_logicf_stage_i_5aade6_idx'),
        ),
        migrations.AddIndex(
            model_name='logicfollowup',
            index=models.Index(fields=['question'], name='form_logicf_questio_cf3e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='logic',
            index=models.Index(fields=['form'], name='form_logic_form_id_fa681f_idx'),
        ),
        migrations.AddIndex(
            model_name='logic',
            index=models.Index(fields=['stage'], name='form_logic_stage_i_1ac7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='logic',
            index=models.Index(fields=['question'], name='form_logic_questio_eb1b64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='logic',
            unique_together={('form', 'stage', 'audit_info', 'audit_group', 'logic_type', 'logic_value')},
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['status'], name='form_follow_status_b8851d_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['deadline_at'], name='form_follow_deadlin_242407_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['main_form_submission'], name='form_follow_main_fo_94a80f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stageaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_type', 'user'), ('allow_user__isnull', False)), models.Q(('access_type', 'group'), ('allow_group__isnull', False)), models.Q(('access_type', 'previous_stage'), ('allow_stage__isnull', False)), models.Q(('access_type', 'organization'), ('allow_group__isnull', True), ('allow_stage__isnull', True), ('allow_user__isnull', True)), _connector='OR'), name='valid_access_rule_type'),
        ),
        migrations.AddIndex(
            model_name='taskclosequestion',
            index=models.Index(fields=['task', 'question'], name='form_taskcl_task_id_45a1ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskclosequestion',
            unique_together={('task', 'question')},
        ),
    ]
