# Generated by Django 5.2.2 on 2026-07-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_optionlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionList',
        ),
    ]
