# Generated by Django 5.2.2 on 2026-08-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_add_collaborative_audit_delegation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditgroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='formsubmision',
            name='is_bulk_imported',
            field=models.BooleanField(default=False, help_text='True if this submission was created via the bulk import responses feature'),
        ),
    ]
