# Generated by Django 5.2.2 on 2026-07-02 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(help_text='Final playable URL (e.g. Cinema8 or YouTube)')),
                ('duration', models.CharField(blank=True, help_text="e.g. '10 mins'", max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learning_course',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LearningCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='assigned', max_length=20)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Learning Course Assignment',
                'verbose_name_plural': 'Learning Course Assignments',
                'db_table': 'learning_course_assignment',
            },
        ),
    ]
