# Generated by Django 5.2.2 on 2026-07-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcourse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningcourse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_courses', to='user.organization'),
        ),
        migrations.AddField(
            model_name='learningcourse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_courses_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningcourseassignment',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_assignments', to='user.groups'),
        ),
        migrations.AddField(
            model_name='learningcourseassignment',
            name='assigned_location_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_assignments', to='user.locationleader'),
        ),
        migrations.AddField(
            model_name='learningcourseassignment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningcourseassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_courses_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningcourseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.learningcourse'),
        ),
    ]
