# Generated by Django 5.2.2 on 2026-07-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_ld_extended_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='selected_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='access_mode',
            field=models.CharField(default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='allow_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='allow_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='allow_skip_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='asset_type',
            field=models.CharField(default='document', help_text='document, video, image', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='certificate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='certificate_validity_unit',
            field=models.CharField(default='year', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='certificate_validity_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lt_training_items/'),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='follow_up_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='follow_up_type',
            field=models.CharField(blank=True, help_text='quiz, video, training', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='pass_percentage',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='questions_per_user',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='reassign_on_fail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='reschedule_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='selected_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='source_type',
            field=models.CharField(default='url', help_text='url or upload', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='grace_time',
            field=models.IntegerField(default=15, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='lt_content_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='repeat_pattern',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='trainer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='trainer_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='training_type',
            field=models.CharField(default='classroom', help_text='classroom, online, hybrid, on-the-job', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='venue_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='venue_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='access_mode',
            field=models.CharField(default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='allow_skip_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='certificate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='certificate_validity_unit',
            field=models.CharField(default='year', max_length=20),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='certificate_validity_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='pass_percentage',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='questions_per_user',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='reassign_on_fail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='reschedule_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='selected_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lt_videos/'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_source',
            field=models.CharField(default='url', help_text='url or upload', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='trigger',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('30-days', '30 Days Before'), ('15-days', '15 Days Before'), ('7-days', '7 Days Before'), ('3-days', '3 Days Before'), ('1-day', '1 Day Before'), ('1-hour', '1 Hour Before'), ('15-minutes', '15 Minutes Before'), ('on-completion', 'On Completion'), ('on-failure', 'On Failure')], default='immediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('training-created', 'Training Created'), ('training-modified', 'Training Modified'), ('training-cancelled', 'Training Cancelled'), ('training-reminder', 'Training Reminder'), ('venue-changed', 'Venue Changed'), ('trainer-changed', 'Trainer Changed'), ('enrollment-approved', 'Enrollment Approved'), ('enrollment-rejected', 'Enrollment Rejected'), ('enrollment-request', 'Enrollment Request'), ('quiz-assigned', 'Quiz Assigned'), ('quiz-completed', 'Quiz Completed'), ('quiz-failed', 'Quiz Failed'), ('certificate-issued', 'Certificate Issued'), ('video-assigned', 'Video Assigned'), ('video-completed', 'Video Completed'), ('training-completed', 'Training Completed'), ('approval-request', 'Approval Request'), ('approval-approved', 'Approval Approved'), ('approval-rejected', 'Approval Rejected')], default='training-created', max_length=30),
        ),
    ]
