# Generated by Django 5.2.2 on 2026-07-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_add_lt_module_full_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='selected_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='selected_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='selected_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='selected_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='selected_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='selected_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
