# Generated by Django 5.2.2 on 2026-07-23 17:16

import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_add_selected_groups_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=learning.models.training_file_upload_path),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=learning.models.video_file_upload_path),
        ),
    ]
