# Generated by Django 5.2.2 on 2026-07-23 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_quiz_result_model'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_department', models.CharField(blank=True, max_length=255, null=True)),
                ('quiz_id', models.IntegerField()),
                ('quiz_title', models.CharField(blank=True, max_length=500, null=True)),
                ('training_type', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.FloatField(default=0)),
                ('pass_percentage', models.FloatField(default=70)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('validity_value', models.IntegerField(default=1)),
                ('validity_unit', models.CharField(default='years', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('organization_name', models.CharField(default='VIBRO Learning, Training & Development', max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='user.organization')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='learning.quizresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lt_certificate',
                'ordering': ['-issued_at'],
            },
        ),
    ]
