# Generated by Django 5.2.2 on 2026-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_certificate_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='approval_chain',
            field=models.JSONField(blank=True, default=list, help_text='List of {level, approver_id, approver_name}'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='training_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
