# Generated by Django 5.2.2 on 2026-07-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_update_enrollment_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
