# Generated by Django 5.2.2 on 2026-07-25 13:23

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_add_enrollment_title'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('training-created', 'Training Created'), ('training-modified', 'Training Modified'), ('training-cancelled', 'Training Cancelled'), ('training-reminder', 'Training Reminder'), ('training-completed', 'Training Completed'), ('venue-changed', 'Venue Changed'), ('trainer-changed', 'Trainer Changed'), ('enrollment-approved', 'Enrollment Approved'), ('enrollment-rejected', 'Enrollment Rejected'), ('enrollment-request', 'Enrollment Request'), ('quiz-assigned', 'Quiz Assigned'), ('quiz-completed', 'Quiz Completed'), ('quiz-failed', 'Quiz Failed'), ('certificate-issued', 'Certificate Issued'), ('video-assigned', 'Video Assigned'), ('video-completed', 'Video Completed'), ('approval-request', 'Approval Request'), ('approval-approved', 'Approval Approved'), ('approval-rejected', 'Approval Rejected')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, help_text='quiz, video, training-schedule', max_length=20, null=True)),
                ('content_id', models.CharField(blank=True, max_length=50, null=True)),
                ('content_title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lt_notifications', to='user.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lt_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lt_notification_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
