# Generated by Django 5.2.2 on 2026-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_add_notification_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='notification_lead_unit',
            field=models.CharField(default='days', help_text='days, hours, weeks, months', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='notification_lead_value',
            field=models.IntegerField(default=0, help_text='How long before training to notify user'),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='approval_chain',
            field=models.JSONField(blank=True, default=list, help_text='List of {level, approver_id, approver_name}'),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='approval_type',
            field=models.CharField(default='none', help_text='none, single-stage, multi-stage', max_length=20),
        ),
    ]
