# Generated by Django 5.2.2 on 2026-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_add_approval_and_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='schedule_id',
            field=models.IntegerField(blank=True, help_text='TrainingSchedule id if this result was taken as part of a training schedule', null=True),
        ),
    ]
