
export const answer = {
    "id": 83,
    "stages": [
        {
            "id": 164,
            "questions": [
                {
                    "id": 432,
                    "options": [],
                    "question_uuid": "q1753873710078-487en8",
                    "question": "select your location",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "location",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 1,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 432,
                        "question_type": "location",
                        "answer": "1",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": 1,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.593364Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 433,
                    "options": [],
                    "question_uuid": "q1753873726479-05p8hg",
                    "question": "select division",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "division",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 2,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 433,
                        "question_type": "division",
                        "answer": "3",
                        "Form": 83,
                        "stage": 164,
                        "division": 3,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.613382Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 434,
                    "options": [],
                    "question_uuid": "q1753873741647-7kl7vv",
                    "question": "select sub division",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "sub_division",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 3,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 434,
                        "question_type": "sub_division",
                        "answer": "5",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": 5,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.624656Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 435,
                    "options": [],
                    "question_uuid": "q1753873763158-kcksk2",
                    "question": "enter the title descrption",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "title_and_description",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 4,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 435,
                        "question_type": "title_and_description",
                        "answer": "Title",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.642198Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 436,
                    "options": [],
                    "question_uuid": "q1753873793054-jjz397",
                    "question": "enter yes or no",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "short_answer",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 5,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 436,
                        "question_type": "short_answer",
                        "answer": "No",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.654816Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 437,
                    "options": [],
                    "question_uuid": "q1753873806935-vk8uh9",
                    "question": "enter your full name with phone number",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "long_answer",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 6,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 437,
                        "question_type": "long_answer",
                        "answer": "Ramkumar Raja 9176086844",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.668162Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 438,
                    "options": [
                        {
                            "id": 140,
                            "created_at": "2025-07-30T12:41:49.078337Z",
                            "updated_at": null,
                            "option": "opt1",
                            "score": 0,
                            "failed": false,
                            "order": 1,
                            "question": 438,
                            "stage": 164,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        },
                        {
                            "id": 141,
                            "created_at": "2025-07-30T12:41:49.092423Z",
                            "updated_at": null,
                            "option": "opt2",
                            "score": 0,
                            "failed": false,
                            "order": 2,
                            "question": 438,
                            "stage": 164,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        }
                    ],
                    "question_uuid": "q1753873843782-hyjd2u",
                    "question": "select any of the choose",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "multiple_choice",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 7,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 438,
                        "question_type": "multiple_choice",
                        "answer": "140",
                        "other_text": null,
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.681192Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 439,
                    "options": [
                        {
                            "id": 142,
                            "created_at": "2025-07-30T12:41:49.123790Z",
                            "updated_at": null,
                            "option": "opt1",
                            "score": 0,
                            "failed": false,
                            "order": 1,
                            "question": 439,
                            "stage": 164,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        },
                        {
                            "id": 143,
                            "created_at": "2025-07-30T12:41:49.134763Z",
                            "updated_at": null,
                            "option": "opt2",
                            "score": 0,
                            "failed": false,
                            "order": 2,
                            "question": 439,
                            "stage": 164,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        }
                    ],
                    "question_uuid": "q1753873887454-94gm3g",
                    "question": "select the dropdown",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "dropdown",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 8,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 439,
                        "question_type": "dropdown",
                        "answer": "142",
                        "other_text": null,
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.697961Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 440,
                    "options": [
                        {
                            "id": 144,
                            "created_at": "2025-07-30T12:41:49.163247Z",
                            "updated_at": null,
                            "option": "start",
                            "score": 0,
                            "failed": false,
                            "order": 1,
                            "question": 440,
                            "stage": 164,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        },
                        {
                            "id": 145,
                            "created_at": "2025-07-30T12:41:49.178239Z",
                            "updated_at": null,
                            "option": "end",
                            "score": 0,
                            "failed": false,
                            "order": 2,
                            "question": 440,
                            "stage": 164,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        }
                    ],
                    "question_uuid": "q1753873913559-uw9n0f",
                    "question": "rate us",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "linear_scale",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 9,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": 6,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 440,
                        "question_type": "linear_scale",
                        "answer": "4",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.711989Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 441,
                    "options": [],
                    "question_uuid": "q1753873938127-k8ayed",
                    "question": "select date time",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "datetime",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 10,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 441,
                        "question_type": "datetime",
                        "answer": "2025-07-30T12:43:00.000Z",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.723055Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 442,
                    "options": [],
                    "question_uuid": "q1753873955551-ea6hmp",
                    "question": "select tomorrow date",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "date",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 11,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 442,
                        "question_type": "date",
                        "answer": "2025-07-30T12:43:00.000Z",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.737554Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 443,
                    "options": [],
                    "question_uuid": "q1753873976582-l9qo03",
                    "question": "enter current time",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "time",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 12,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 443,
                        "question_type": "time",
                        "answer": "2025-07-30T12:43:00.000Z",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.751383Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 444,
                    "options": [],
                    "question_uuid": "q1753873998958-yda8ku",
                    "question": "give your sign",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "signature",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 13,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 444,
                        "question_type": "signature",
                        "answer": "https://res.cloudinary.com/dxppo6n3w/image/upload/v1753879427/vibrofiles/zbhtuagryxexyiprpdqh.png",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.764449Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 445,
                    "options": [],
                    "question_uuid": "q1753874017174-usbl7l",
                    "question": "upload any image",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "upload_image",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 14,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 445,
                        "question_type": "upload_image",
                        "answer": "https://res.cloudinary.com/dxppo6n3w/image/upload/v1753879433/vibrofiles/dhkwstlylv4fugibxudx.jpg",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.777920Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 446,
                    "options": [],
                    "question_uuid": "q1753874036078-cn8tjd",
                    "question": "upload video of your",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "upload_video",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 15,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 446,
                        "question_type": "upload_video",
                        "answer": "https://res.cloudinary.com/dxppo6n3w/video/upload/v1753879445/vibrofiles/qb1zxlcax8onsfl5cdeq.mp4",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.794740Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 447,
                    "options": [],
                    "question_uuid": "q1753874064102-3ducme",
                    "question": "enter your file",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "upload_file",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 16,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 447,
                        "question_type": "upload_file",
                        "answer": "undefined",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.807071Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 448,
                    "options": [],
                    "question_uuid": "q1753874076806-o5f48l",
                    "question": "scan the QR",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "qr_code",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 17,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 448,
                        "question_type": "qr_code",
                        "answer": "Hello :)",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.821266Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 449,
                    "options": [],
                    "question_uuid": "q1753874118367-ua4ejh",
                    "question": "select org",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "user",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 18,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 164,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 449,
                        "question_type": "user",
                        "answer": "25",
                        "Form": 83,
                        "stage": 164,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": 25,
                        "submitted_by": 85,
                        "submitted_on": "2025-07-30T12:44:40.837007Z",
                        "submission": 15,
                        "organization": 13
                    }
                }
            ],
            "created_at": "2025-07-30T12:41:48.991054Z",
            "updated_at": null,
            "name": "Stage 1",
            "stage_uuid": "dedab79e-b880-44d4-9eb3-ee012766767094c21",
            "order": 1,
            "form": 83,
            "is_completed": true,
            "completed_by": 85,
            "completed_on": "2025-07-30T12:44:40.843114Z"
        },
        {
            "id": 165,
            "questions": [
                {
                    "id": 450,
                    "options": [],
                    "question_uuid": "qgixagxr1pol",
                    "question": "select your location",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "location",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 1,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 450,
                        "question_type": "location",
                        "answer": "1",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": 1,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T12:50:32.815600Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 451,
                    "options": [],
                    "question_uuid": "q9uliw3a6c6t",
                    "question": "select division",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "division",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 2,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 451,
                        "question_type": "division",
                        "answer": "2",
                        "Form": 83,
                        "stage": 165,
                        "division": 2,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T12:50:32.837600Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 452,
                    "options": [],
                    "question_uuid": "qki1hxycqo5",
                    "question": "select sub division",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "sub_division",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 3,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 452,
                        "question_type": "sub_division",
                        "answer": "1",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": 1,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.414332Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 453,
                    "options": [],
                    "question_uuid": "qcag21b70imi",
                    "question": "enter the title descrption",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "title_and_description",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 4,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 453,
                        "question_type": "title_and_description",
                        "answer": "Uud",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.430041Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 454,
                    "options": [],
                    "question_uuid": "qberdqljcrtk",
                    "question": "enter yes or no",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "short_answer",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 5,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 454,
                        "question_type": "short_answer",
                        "answer": "No",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.446457Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 455,
                    "options": [],
                    "question_uuid": "qg100b7as6hn",
                    "question": "enter your full name with phone number",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "long_answer",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 6,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 455,
                        "question_type": "long_answer",
                        "answer": "Hdjej",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.460875Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 456,
                    "options": [
                        {
                            "id": 146,
                            "created_at": "2025-07-30T12:41:49.427533Z",
                            "updated_at": null,
                            "option": "opt1",
                            "score": 0,
                            "failed": false,
                            "order": 1,
                            "question": 456,
                            "stage": 165,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        },
                        {
                            "id": 147,
                            "created_at": "2025-07-30T12:41:49.440128Z",
                            "updated_at": null,
                            "option": "opt2",
                            "score": 0,
                            "failed": false,
                            "order": 2,
                            "question": 456,
                            "stage": 165,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        }
                    ],
                    "question_uuid": "q7ba427odiz4",
                    "question": "select any of the choose",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "multiple_choice",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 7,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 456,
                        "question_type": "multiple_choice",
                        "answer": "146",
                        "other_text": null,
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.479268Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 457,
                    "options": [
                        {
                            "id": 148,
                            "created_at": "2025-07-30T12:41:49.464280Z",
                            "updated_at": null,
                            "option": "opt1",
                            "score": 0,
                            "failed": false,
                            "order": 1,
                            "question": 457,
                            "stage": 165,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        },
                        {
                            "id": 149,
                            "created_at": "2025-07-30T12:41:49.476341Z",
                            "updated_at": null,
                            "option": "opt2",
                            "score": 0,
                            "failed": false,
                            "order": 2,
                            "question": 457,
                            "stage": 165,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        }
                    ],
                    "question_uuid": "qkn2nqnhhia",
                    "question": "select the dropdown",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "dropdown",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 8,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 457,
                        "question_type": "dropdown",
                        "answer": "148",
                        "other_text": null,
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.493957Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 458,
                    "options": [
                        {
                            "id": 150,
                            "created_at": "2025-07-30T12:41:49.502764Z",
                            "updated_at": null,
                            "option": "start",
                            "score": 0,
                            "failed": false,
                            "order": 1,
                            "question": 458,
                            "stage": 165,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        },
                        {
                            "id": 151,
                            "created_at": "2025-07-30T12:41:49.516240Z",
                            "updated_at": null,
                            "option": "end",
                            "score": 0,
                            "failed": false,
                            "order": 2,
                            "question": 458,
                            "stage": 165,
                            "audit_info": null,
                            "audit_group": null,
                            "form": 83
                        }
                    ],
                    "question_uuid": "q7io4k7xufm7",
                    "question": "rate us",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "linear_scale",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 9,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": 6,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 458,
                        "question_type": "linear_scale",
                        "answer": "4",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.509455Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 459,
                    "options": [],
                    "question_uuid": "q4lyyb62irzi",
                    "question": "select date time",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "datetime",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 10,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 459,
                        "question_type": "datetime",
                        "answer": "2025-07-30T12:58:00.000Z",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.528102Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 460,
                    "options": [],
                    "question_uuid": "qo4700hiiv9s",
                    "question": "select tomorrow date",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "date",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 11,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 460,
                        "question_type": "date",
                        "answer": "2025-07-30T12:58:00.000Z",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.548326Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 461,
                    "options": [],
                    "question_uuid": "qn6c10904xq",
                    "question": "enter current time",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "time",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 12,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 461,
                        "question_type": "time",
                        "answer": "2025-07-30T12:59:00.000Z",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.562039Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 462,
                    "options": [],
                    "question_uuid": "qdmx4vnjfx2k",
                    "question": "give your sign",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "signature",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 13,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 462,
                        "question_type": "signature",
                        "answer": "https://res.cloudinary.com/dxppo6n3w/image/upload/v1753880343/vibrofiles/rlrms8irfjb1wmot6rpy.png",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.575761Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 463,
                    "options": [],
                    "question_uuid": "q17ohlwma78i",
                    "question": "upload any image",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "upload_image",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 14,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 463,
                        "question_type": "upload_image",
                        "answer": "https://res.cloudinary.com/dxppo6n3w/image/upload/v1753880355/vibrofiles/inrzixapogwqnu5v45uv.jpg",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.590429Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 464,
                    "options": [],
                    "question_uuid": "qhxpsa3f7n1f",
                    "question": "upload video of your",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "upload_video",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 15,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 464,
                        "question_type": "upload_video",
                        "answer": "https://res.cloudinary.com/dxppo6n3w/video/upload/v1753880363/vibrofiles/jpoubcxwnyxta2ivfxmo.mp4",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.603896Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 465,
                    "options": [],
                    "question_uuid": "qxid6artegjk",
                    "question": "enter your file",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "upload_file",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 16,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 465,
                        "question_type": "upload_file",
                        "answer": "undefined",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.615774Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 466,
                    "options": [],
                    "question_uuid": "qmpvwyrkdpg",
                    "question": "scan the QR",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "qr_code",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 17,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 466,
                        "question_type": "qr_code",
                        "answer": "Hello :)",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": null,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.629152Z",
                        "submission": 15,
                        "organization": 13
                    }
                },
                {
                    "id": 467,
                    "options": [],
                    "question_uuid": "qojgbcemutk",
                    "question": "select org",
                    "description": null,
                    "critical": false,
                    "formula": null,
                    "question_type": "user",
                    "question_sub_type": null,
                    "question_hint": null,
                    "order": 18,
                    "is_required": false,
                    "require_live": false,
                    "number_of_file_allowed": null,
                    "min_value": null,
                    "max_value": null,
                    "max_score": null,
                    "is_logic_question": false,
                    "is_task_close_question": false,
                    "is_audit_info_question": false,
                    "is_other": false,
                    "form": 83,
                    "stage": 165,
                    "audit_info": null,
                    "audit_group": null,
                    "parent_question": null,
                    "sub_questions": [],
                    "logics": [],
                    "answers": {
                        "question": 467,
                        "question_type": "user",
                        "answer": "33",
                        "Form": 83,
                        "stage": 165,
                        "division": null,
                        "sub_division": null,
                        "location": null,
                        "user": 33,
                        "submitted_by": 25,
                        "submitted_on": "2025-07-30T13:05:31.644238Z",
                        "submission": 15,
                        "organization": 13
                    }
                }
            ],
            "created_at": "2025-07-30T12:41:49.342271Z",
            "updated_at": null,
            "name": "Stage 2",
            "stage_uuid": "dedab79e-b880-44d4-9eb3-evdtrsxf67094c21",
            "order": 2,
            "form": 83,
            "is_completed": true,
            "completed_by": 25,
            "completed_on": "2025-07-30T13:05:31.653751Z"
        }
    ],
    "audit_info": null,
    "audit_group": [],
    "created_at": "2025-07-30T12:41:48.899844Z",
    "updated_at": null,
    "form_type": "standard",
    "title": "testing all question types",
    "prefix": "",
    "GPS": false,
    "share_response": false,
    "allow_editing": false,
    "can_edit_previous_state": false,
    "auto_share_response": false,
    "pass_percentage": 70,
    "max_score": 100,
    "is_deleted": false,
    "is_archived": false,
    "last_deleted_date": null,
    "last_archived_date": null,
    "created_by": 85,
    "updated_by": null,
    "organization": 13,
    "folder": 13,
    "form_admin": 85,
    "deletedBy": null,
    "archivedBy": null,
    "submissionsDetail": {
        "id": 15,
        "form": 83,
        "submission_initiated_stage": 164,
        "submission_initiated_on": "2025-07-30T12:44:40.552712Z",
        "submission_initiated_by": 85,
        "is_completed": true,
        "completed_by": 25,
        "completed_on": "2025-07-30T13:05:31.658842Z"
    }
}

export const submissions = [
    {
        "id": 15,
        "form": 83,
        "submission_initiated_stage": 164,
        "submission_initiated_on": "2025-07-30T12:44:40.552712Z",
        "submission_initiated_by": 85,
        "is_completed": true,
        "completed_by": 25,
        "completed_on": "2025-07-30T13:05:31.658842Z"
    },
    {
        "id": 16,
        "form": 84,
        "submission_initiated_stage": 165,
        "submission_initiated_on": "2025-08-01T12:44:40.552712Z",
        "submission_initiated_by": 86,
        "is_completed": true,
        "completed_by": 25,
        "completed_on": "2025-07-30T13:05:31.658842Z"
    }
]
