# Generated by Django 5.2.2 on 2026-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_id', models.BigIntegerField(null=True, unique=True)),
                ('form_id', models.IntegerField()),
                ('s3_key', models.CharField(max_length=255)),
                ('s3_url', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('form_overall_status', models.CharField(blank=True, max_length=50, null=True)),
                ('form_overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form_critical_failed', models.IntegerField(blank=True, default=0, null=True)),
                ('groups_status', models.CharField(blank=True, max_length=50, null=True)),
                ('group_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('group_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('group_critical_failed', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
