# Generated by Django 5.2.2 on 2026-07-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draft', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='audit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.auditinfo'),
        ),
    ]
