# Generated by Django 5.2.2 on 2026-07-07 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together={('user', 'draft_id')},
        ),
    ]
