# Generated by Django 5.2.2 on 2026-07-02 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('announcement_category', models.CharField(max_length=250)),
                ('announcement_start_date', models.DateTimeField()),
                ('announcement_end_date', models.DateTimeField()),
                ('pin_as_important', models.BooleanField(default=False)),
                ('request_acknowledge', models.BooleanField(default=False)),
                ('prevent_download', models.BooleanField(default=False)),
                ('announcement_content', models.TextField()),
                ('announcement_tags', models.TextField(blank=True, null=True)),
                ('announcement_attachments', models.TextField(blank=True, null=True)),
                ('announcement_attachments_urls', models.TextField(blank=True, null=True)),
                ('announcement_fullscreen', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'announcement_details',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementShareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('acknowledged', 'Acknowledged'), ('notified', 'Notified'), ('liked', 'Liked')], db_column='announcement_share_status', default='sent', max_length=300)),
                ('sent_timestamp', models.DateTimeField(db_column='announcement_sent_timestamp', default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(db_column='announcement_acknowledged', default=False)),
                ('acknowledged_timestamp', models.DateTimeField(blank=True, db_column='announcement_acknowledged_timestamp', null=True)),
                ('viewed_timestamp', models.DateTimeField(blank=True, db_column='announcement_viewed_timestamp', null=True)),
                ('liked', models.BooleanField(db_column='announcement_liked', default=False)),
            ],
            options={
                'db_table': 'announcement_share_info',
            },
        ),
    ]
