# Generated by Django 5.2.2 on 2026-07-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementshareinfo',
            name='announcement',
            field=models.ForeignKey(db_column='announcement_id', on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
        migrations.AddField(
            model_name='announcementshareinfo',
            name='sent_to_group',
            field=models.ForeignKey(blank=True, db_column='announcement_sent_to_groups', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_shares_group', to='user.groups'),
        ),
        migrations.AddField(
            model_name='announcementshareinfo',
            name='sent_to_user',
            field=models.ForeignKey(blank=True, db_column='announcement_sent_to_users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_shares_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
