# Generated by Django 5.2.2 on 2026-07-08 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcementcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementcategory',
            options={'verbose_name_plural': 'Announcement Categories'},
        ),
        migrations.RemoveField(
            model_name='announcementcategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='announcementcategory',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='announcementcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcementcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
