# Generated by Django 5.2.2 on 2026-08-07 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_modulepermisions_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guide_folders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_folders', to='user.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='guide.guidefolder')),
            ],
            options={
                'db_table': 'guide_folder',
                'ordering': ['name'],
                'unique_together': {('name', 'parent', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='GuideDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='guide_documents/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('document_type', models.CharField(choices=[('sop', 'SOP'), ('tutorial', 'Tutorial'), ('qap', 'QAP'), ('drawing', 'Drawing'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_print', models.BooleanField(default=True)),
                ('allow_screenshot', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_documents', to='user.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_guides', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guide.guidefolder')),
            ],
            options={
                'db_table': 'guide_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], default='user', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='guide.guidedocument')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='guide.guidefolder')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_guides', to=settings.AUTH_USER_MODEL)),
                ('shared_with_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_guide_shares', to='user.groups')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_guide_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guide_share',
                'ordering': ['-created_at'],
            },
        ),
    ]
