export default [
  {
    id: 72,
    questions: [
      {
        id: 189,
        options: [],
        question_uuid: "question_uuid1",
        question: "Stage 1 - Question 1 - table",
        description: null,
        critical: false,
        formula: null,
        question_type: "table",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: 1,
        max_value: 2,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 72,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [
          {
            id: 190,
            options: [],
            question_uuid: "question_uuid2",
            question: "Stage 1 - Table Child Question 1 - location",
            description: null,
            critical: false,
            formula: null,
            question_type: "location",
            question_sub_type: null,
            question_hint: null,
            order: 1,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: false,
            form: 64,
            stage: 72,
            audit_info: null,
            audit_group: null,
            parent_question: 189,
            sub_questions: [],
            logics: [],
            answer: {
              question_uuid: "question_uuid13",
              question: 201,
              question_type: "location",
              answer: "3",
              stage: 72,
              group: null,
              division: null,
              sub_division: null,
              location: 3,
              user: null,
            },
          },
          {
            id: 191,
            options: [],
            question_uuid: "question_uuid3",
            question: "Stage 1 - Table Child Question 2 - division",
            description: null,
            critical: false,
            formula: null,
            question_type: "division",
            question_sub_type: null,
            question_hint: null,
            order: 2,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: false,
            form: 64,
            stage: 72,
            audit_info: null,
            audit_group: null,
            parent_question: 189,
            sub_questions: [],
            logics: [],
          },
          {
            id: 192,
            options: [
              {
                id: 40,
                created_at: "2025-07-10T18:34:31.922068Z",
                updated_at: null,
                option: "Stage 1 - Table Child Question 3 - Option 1",
                score: 0,
                failed: false,
                order: 1,
                question: 192,
                stage: 72,
                audit_info: null,
                audit_group: null,
                form: 64,
              },
              {
                id: 41,
                created_at: "2025-07-10T18:34:31.933327Z",
                updated_at: null,
                option: "Stage 1 - Table Child Question 3 - Option 2",
                score: 0,
                failed: false,
                order: 2,
                question: 192,
                stage: 72,
                audit_info: null,
                audit_group: null,
                form: 64,
              },
              {
                id: 42,
                created_at: "2025-07-10T18:34:31.942794Z",
                updated_at: null,
                option: "Stage 1 - Table Child Question 3 - Option 3",
                score: 0,
                failed: false,
                order: 3,
                question: 192,
                stage: 72,
                audit_info: null,
                audit_group: null,
                form: 64,
              },
            ],
            question_uuid: "question_uuid4",
            question: "Stage 1 - Table Child Question 3 - dropdown",
            description: null,
            critical: false,
            formula: null,
            question_type: "dropdown",
            question_sub_type: "text",
            question_hint: null,
            order: 3,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: true,
            form: 64,
            stage: 72,
            audit_info: null,
            audit_group: null,
            parent_question: 189,
            sub_questions: [],
            logics: [],
          },
        ],
        logics: [
          {
            id: 1,
            logic_questions: [
              {
                id: 193,
                options: [],
                created_at: "2025-07-10T18:34:31.961355Z",
                updated_at: null,
                question_uuid: "question_uuid7",
                question: "Logic 1 question 1",
                description: null,
                critical: false,
                formula: null,
                question_type: "division",
                question_sub_type: null,
                question_hint: null,
                order: 1,
                is_required: true,
                require_live: false,
                number_of_file_allowed: null,
                min_value: 1,
                max_value: 2,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 64,
                stage: 72,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
              {
                id: 194,
                options: [],
                created_at: "2025-07-10T18:34:31.976462Z",
                updated_at: null,
                question_uuid: "question_uuid8",
                question: "Logic 1 question 2",
                description: null,
                critical: false,
                formula: null,
                question_type: "division",
                question_sub_type: null,
                question_hint: null,
                order: 2,
                is_required: true,
                require_live: false,
                number_of_file_allowed: null,
                min_value: 1,
                max_value: 2,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 64,
                stage: 72,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-10T18:34:31.954616Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "YES",
            notification: false,
            email: null,
            order: 1,
            user: null,
            group: null,
            form: 64,
            stage: 72,
            audit_info: null,
            audit_group: null,
            question: 189,
            follow_up: {
              task_close_questions: [
                {
                  id: 195,
                  options: [],
                  created_at: "2025-07-10T18:34:32.006642Z",
                  updated_at: null,
                  question_uuid: "question_uuid5",
                  question: "LOGIC 1 - FOLLOW UP TASK CLOSE QUESTION 1",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "date",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: true,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: false,
                  is_task_close_question: true,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 64,
                  stage: 72,
                  audit_info: null,
                  audit_group: null,
                  parent_question: null,
                },
                {
                  id: 196,
                  options: [],
                  created_at: "2025-07-10T18:34:32.019854Z",
                  updated_at: null,
                  question_uuid: "question_uuid6",
                  question: "LOGIC 1 - FOLLOW UP TASK CLOSE QUESTION 2",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "time",
                  question_sub_type: null,
                  question_hint: null,
                  order: 2,
                  is_required: true,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: false,
                  is_task_close_question: true,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 64,
                  stage: 72,
                  audit_info: null,
                  audit_group: null,
                  parent_question: null,
                },
              ],
              title: "LOGIC 1 - Followup title 1",
              deadline: 30,
              assign_to: "form_submitter",
              logic: 1,
              assign_form: null,
              user: null,
              group: null,
              form: 64,
              stage: 72,
              audit_info: null,
              audit_group: null,
              question: 189,
            },
          },
          {
            id: 2,
            logic_questions: [
              {
                id: 197,
                options: [],
                created_at: "2025-07-10T18:34:32.039677Z",
                updated_at: null,
                question_uuid: "question_uuid11",
                question: "Logic 2 question 1",
                description: null,
                critical: false,
                formula: null,
                question_type: "division",
                question_sub_type: null,
                question_hint: null,
                order: 1,
                is_required: true,
                require_live: false,
                number_of_file_allowed: null,
                min_value: 1,
                max_value: 2,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 64,
                stage: 72,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
              {
                id: 198,
                options: [],
                created_at: "2025-07-10T18:34:32.044801Z",
                updated_at: null,
                question_uuid: "question_uuid12",
                question: "Logic 2 question 2",
                description: null,
                critical: false,
                formula: null,
                question_type: "division",
                question_sub_type: null,
                question_hint: null,
                order: 2,
                is_required: true,
                require_live: false,
                number_of_file_allowed: null,
                min_value: 1,
                max_value: 2,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 64,
                stage: 72,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-10T18:34:32.034553Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "NO",
            notification: false,
            email: null,
            order: 2,
            user: null,
            group: null,
            form: 64,
            stage: 72,
            audit_info: null,
            audit_group: null,
            question: 189,
            follow_up: {
              task_close_questions: [
                {
                  id: 199,
                  options: [],
                  created_at: "2025-07-10T18:34:32.055434Z",
                  updated_at: null,
                  question_uuid: "question_uuid9",
                  question: "LOGIC 2 - FOLLOW UP TASK CLOSE QUESTION 1",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "date",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: true,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: false,
                  is_task_close_question: true,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 64,
                  stage: 72,
                  audit_info: null,
                  audit_group: null,
                  parent_question: null,
                },
                {
                  id: 200,
                  options: [],
                  created_at: "2025-07-10T18:34:32.062335Z",
                  updated_at: null,
                  question_uuid: "question_uuid10",
                  question: "LOGIC 2 - FOLLOW UP TASK CLOSE QUESTION 1",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "time",
                  question_sub_type: null,
                  question_hint: null,
                  order: 2,
                  is_required: true,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: false,
                  is_task_close_question: true,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 64,
                  stage: 72,
                  audit_info: null,
                  audit_group: null,
                  parent_question: null,
                },
              ],
              title: "LOGIC 2 - Followup title 2",
              deadline: 30,
              assign_to: "form_submitter",
              logic: 2,
              assign_form: null,
              user: null,
              group: null,
              form: 64,
              stage: 72,
              audit_info: null,
              audit_group: null,
              question: 189,
            },
          },
        ],
      },
      {
        id: 201,
        options: [],
        question_uuid: "question_uuid13",
        question: "Stage 2- Question 2 - location",
        description: null,
        critical: false,
        formula: null,
        question_type: "location",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 72,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:31.838232Z",
    updated_at: null,
    name: "Stage 1",
    order: 1,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 73,
    questions: [
      {
        id: 202,
        options: [],
        question_uuid: "question_uuid14",
        question: "Stage 2 - Question 1 - division",
        description: null,
        critical: false,
        formula: null,
        question_type: "division",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 73,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 203,
        options: [],
        question_uuid: "question_uuid15",
        question: "Stage 2 - Question 2 - sub_division",
        description: null,
        critical: false,
        formula: null,
        question_type: "sub_division",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 73,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.087195Z",
    updated_at: null,
    name: "Stage 2",
    order: 2,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 74,
    questions: [
      {
        id: 204,
        options: [],
        question_uuid: "question_uuid16",
        question: "Stage 3 - Question 1 - title_and_description",
        description: "Question Description",
        critical: false,
        formula: null,
        question_type: "title_and_description",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 74,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 205,
        options: [],
        question_uuid: "question_uuid17",
        question: "Stage 3 - Question 2 - short_answer",
        description: null,
        critical: false,
        formula: null,
        question_type: "short_answer",
        question_sub_type: null,
        question_hint: "Question Hint",
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 74,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.115910Z",
    updated_at: null,
    name: "Stage 3",
    order: 3,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 75,
    questions: [
      {
        id: 206,
        options: [],
        question_uuid: "question_uuid18",
        question: "Stage 4 - Question 1 - long_answer",
        description: null,
        critical: false,
        formula: null,
        question_type: "long_answer",
        question_sub_type: null,
        question_hint: "Question Hint",
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 75,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 207,
        options: [
          {
            id: 43,
            created_at: "2025-07-10T18:34:32.188720Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 1",
            score: 0,
            failed: false,
            order: 1,
            question: 207,
            stage: 75,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
          {
            id: 44,
            created_at: "2025-07-10T18:34:32.197962Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 2",
            score: 0,
            failed: false,
            order: 2,
            question: 207,
            stage: 75,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
          {
            id: 45,
            created_at: "2025-07-10T18:34:32.207784Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 3",
            score: 0,
            failed: false,
            order: 3,
            question: 207,
            stage: 75,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
        ],
        question_uuid: "question_uuid19",
        question: "Stage 4 - Question 2 - multiple_choice",
        description: null,
        critical: false,
        formula: null,
        question_type: "multiple_choice",
        question_sub_type: "text",
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: true,
        form: 64,
        stage: 75,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.158127Z",
    updated_at: null,
    name: "Stage 4",
    order: 4,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 76,
    questions: [
      {
        id: 208,
        options: [
          {
            id: 46,
            created_at: "2025-07-10T18:34:32.255008Z",
            updated_at: null,
            option: "Stage 5 - Question 1 - Option 1",
            score: 0,
            failed: false,
            order: 1,
            question: 208,
            stage: 76,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
          {
            id: 47,
            created_at: "2025-07-10T18:34:32.266870Z",
            updated_at: null,
            option: "Stage 5 - Question 1 - Option 2",
            score: 0,
            failed: false,
            order: 2,
            question: 208,
            stage: 76,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
          {
            id: 48,
            created_at: "2025-07-10T18:34:32.278470Z",
            updated_at: null,
            option: "Stage 5 - Question 1 - Option 3",
            score: 0,
            failed: false,
            order: 3,
            question: 208,
            stage: 76,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
        ],
        question_uuid: "question_uuid20",
        question: "Stage 5 - Question 1 - checkboxes",
        description: null,
        critical: false,
        formula: null,
        question_type: "checkboxes",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 76,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 209,
        options: [
          {
            id: 49,
            created_at: "2025-07-10T18:34:32.300034Z",
            updated_at: null,
            option: "Stage 5 - Question 2 - Option 1",
            score: 0,
            failed: false,
            order: 1,
            question: 209,
            stage: 76,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
          {
            id: 50,
            created_at: "2025-07-10T18:34:32.312415Z",
            updated_at: null,
            option: "Stage 5 - Question 2 - Option 2",
            score: 0,
            failed: false,
            order: 2,
            question: 209,
            stage: 76,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
          {
            id: 51,
            created_at: "2025-07-10T18:34:32.323270Z",
            updated_at: null,
            option: "Stage 5 - Question 2 - Option 3",
            score: 0,
            failed: false,
            order: 3,
            question: 209,
            stage: 76,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
        ],
        question_uuid: "question_uuid21",
        question: "Stage 5 - Question 2 - dropdown",
        description: null,
        critical: false,
        formula: null,
        question_type: "dropdown",
        question_sub_type: "text",
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: true,
        form: 64,
        stage: 76,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.229599Z",
    updated_at: null,
    name: "Stage 5",
    order: 5,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 77,
    questions: [
      {
        id: 210,
        options: [
          {
            id: 52,
            created_at: "2025-07-10T18:34:32.374959Z",
            updated_at: null,
            option: "Stage 6 - Question 1 - Option 1",
            score: 0,
            failed: false,
            order: 1,
            question: 210,
            stage: 77,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
          {
            id: 53,
            created_at: "2025-07-10T18:34:32.383606Z",
            updated_at: null,
            option: "Stage 6 - Question 1 - Option 2",
            score: 0,
            failed: false,
            order: 2,
            question: 210,
            stage: 77,
            audit_info: null,
            audit_group: null,
            form: 64,
          },
        ],
        question_uuid: "question_uuid22",
        question: "Stage 6 - Question 1 - linear_scale",
        description: null,
        critical: false,
        formula: null,
        question_type: "linear_scale",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: 1,
        max_value: 2,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 77,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 211,
        options: [],
        question_uuid: "question_uuid23",
        question: "Stage 6 - Question 2 - datetime",
        description: null,
        critical: false,
        formula: null,
        question_type: "datetime",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 77,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.338689Z",
    updated_at: null,
    name: "Stage 6",
    order: 6,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 78,
    questions: [
      {
        id: 212,
        options: [],
        question_uuid: "question_uuid24",
        question: "Stage 7 - Question 1 - date",
        description: null,
        critical: false,
        formula: null,
        question_type: "date",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 78,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 213,
        options: [],
        question_uuid: "question_uuid25",
        question: "Stage 7 - Question 2 - time",
        description: null,
        critical: false,
        formula: null,
        question_type: "time",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 78,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.405920Z",
    updated_at: null,
    name: "Stage 7",
    order: 7,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 79,
    questions: [
      {
        id: 214,
        options: [],
        question_uuid: "question_uuid26",
        question: "Stage 8 - Question 1 - signature",
        description: null,
        critical: false,
        formula: null,
        question_type: "signature",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 79,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 215,
        options: [],
        question_uuid: "question_uuid27",
        question: "Stage 8 - Question 2 - upload_image",
        description: null,
        critical: false,
        formula: null,
        question_type: "upload_image",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: true,
        number_of_file_allowed: 5,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 79,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 216,
        options: [],
        question_uuid: "question_uuid28",
        question: "Stage 9 - Question 1 - upload_video",
        description: null,
        critical: false,
        formula: null,
        question_type: "upload_video",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: true,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 80,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.432992Z",
    updated_at: null,
    name: "Stage 8",
    order: 8,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 80,
    questions: [
      {
        id: 216,
        options: [],
        question_uuid: "question_uuid28",
        question: "Stage 9 - Question 1 - upload_video",
        description: null,
        critical: false,
        formula: null,
        question_type: "upload_video",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: true,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 80,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 217,
        options: [],
        question_uuid: "question_uuid29",
        question: "Stage 9 - Question 2 - upload_file",
        description: null,
        critical: false,
        formula: null,
        question_type: "upload_file",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: 3,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 80,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.462427Z",
    updated_at: null,
    name: "Stage 9",
    order: 9,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
  {
    id: 81,
    questions: [
      {
        id: 218,
        options: [],
        question_uuid: "question_uuid30",
        question: "Stage 10 - Question 1 - qr_code",
        description: null,
        critical: false,
        formula: null,
        question_type: "qr_code",
        question_sub_type: null,
        question_hint: "Stage 10 - Question 1 - qr_code - Question Hint",
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 81,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
        answer: {
          question_uuid: "question_uuid13",
          question: 201,
          question_type: "location",
          answer: "3",
          stage: 72,
          group: null,
          division: null,
          sub_division: null,
          location: 3,
          user: null,
        },
      },
      {
        id: 219,
        options: [],
        question_uuid: "question_uuid31",
        question: "Stage 10 - Question 2 - formula",
        description: null,
        critical: false,
        formula: "SUM(asdasd+asdasd)*asdsd",
        question_type: "formula",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 81,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 220,
        options: [],
        question_uuid: "question_uuid32",
        question: "Stage 10 - Question 3 - user",
        description: null,
        critical: false,
        formula: null,
        question_type: "user",
        question_sub_type: null,
        question_hint: null,
        order: 3,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 64,
        stage: 81,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-10T18:34:32.491074Z",
    updated_at: null,
    name: "Stage 10",
    order: 10,
    is_completed: false,
    completed_on: null,
    form: 64,
    completed_by: null,
  },
];
