export default [
  {
    id: 95,
    questions: [
      {
        id: 301,
        options: [
          {
            id: 114,
            created_at: "2025-07-29T04:00:04.628967Z",
            updated_at: null,
            option: "yes",
            score: 0,
            failed: false,
            order: 1,
            question: 301,
            stage: 95,
            audit_info: null,
            audit_group: null,
            form: 75,
          },
          {
            id: 115,
            created_at: "2025-07-29T04:00:05.083401Z",
            updated_at: null,
            option: "no",
            score: 0,
            failed: false,
            order: 2,
            question: 301,
            stage: 95,
            audit_info: null,
            audit_group: null,
            form: 75,
          },
          {
            id: 116,
            created_at: "2025-07-29T04:00:05.544770Z",
            updated_at: null,
            option: "NA",
            score: 0,
            failed: false,
            order: 3,
            question: 301,
            stage: 95,
            audit_info: null,
            audit_group: null,
            form: 75,
          },
        ],
        question_uuid: "q1753760456900-d4ilq1",
        question: "do have anything to say",
        description: null,
        critical: false,
        formula: null,
        question_type: "multiple_choice",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: false,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 75,
        stage: 95,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [
          {
            id: 32,
            logic_questions: [
              {
                id: 302,
                options: [],
                created_at: "2025-07-29T04:00:05.872159Z",
                updated_at: null,
                question_uuid: "sub-q1753760662511-ky54zo",
                question: "please describe it here",
                description: null,
                critical: false,
                formula: null,
                question_type: "long_answer",
                question_sub_type: null,
                question_hint: "Question Hint",
                order: 1,
                is_required: false,
                require_live: false,
                number_of_file_allowed: null,
                min_value: null,
                max_value: null,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 75,
                stage: 95,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-29T04:00:05.741684Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "yes",
            notification: false,
            email: null,
            order: 1,
            user: null,
            group: null,
            form: 75,
            stage: 95,
            audit_info: null,
            audit_group: null,
            question: 301,
            follow_up: null,
          },
          {
            id: 33,
            logic_questions: [
              {
                id: 303,
                options: [],
                created_at: "2025-07-29T04:00:06.396273Z",
                updated_at: null,
                question_uuid: "sub-q1753760757509-2g32bq",
                question: "its ok fine provide anything you want",
                description: null,
                critical: false,
                formula: null,
                question_type: "short_answer",
                question_sub_type: null,
                question_hint: "Question Hint",
                order: 1,
                is_required: false,
                require_live: false,
                number_of_file_allowed: null,
                min_value: null,
                max_value: null,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 75,
                stage: 95,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-29T04:00:06.265359Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "NA",
            notification: false,
            email: null,
            order: 1,
            user: null,
            group: null,
            form: 75,
            stage: 95,
            audit_info: null,
            audit_group: null,
            question: 301,
            follow_up: null,
          },
        ],
      },
    ],
    created_at: "2025-07-29T04:00:03.572147Z",
    updated_at: null,
    name: "Multiple Choice logic testing",
    order: 1,
    is_completed: false,
    completed_on: null,
    form: 75,
    completed_by: null,
  },
  {
    id: 96,
    questions: [
      {
        id: 304,
        options: [
          {
            id: 117,
            created_at: "2025-07-29T04:00:08.439699Z",
            updated_at: null,
            option: "yes",
            score: 0,
            failed: false,
            order: 1,
            question: 304,
            stage: 96,
            audit_info: null,
            audit_group: null,
            form: 75,
          },
          {
            id: 118,
            created_at: "2025-07-29T04:00:08.894150Z",
            updated_at: null,
            option: "no",
            score: 0,
            failed: false,
            order: 2,
            question: 304,
            stage: 96,
            audit_info: null,
            audit_group: null,
            form: 75,
          },
          {
            id: 119,
            created_at: "2025-07-29T04:00:09.347594Z",
            updated_at: null,
            option: "ongoing",
            score: 0,
            failed: false,
            order: 3,
            question: 304,
            stage: 96,
            audit_info: null,
            audit_group: null,
            form: 75,
          },
        ],
        question_uuid: "q1753760813011-9j568b",
        question: "is the issue resolved",
        description: null,
        critical: false,
        formula: null,
        question_type: "dropdown",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: false,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 75,
        stage: 96,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [
          {
            id: 34,
            logic_questions: [
              {
                id: 305,
                options: [],
                created_at: "2025-07-29T04:00:09.675356Z",
                updated_at: null,
                question_uuid: "sub-q1753760948728-lg9tld",
                question: "please upload the invoice",
                description: null,
                critical: false,
                formula: null,
                question_type: "upload_image",
                question_sub_type: null,
                question_hint: null,
                order: 1,
                is_required: false,
                require_live: false,
                number_of_file_allowed: null,
                min_value: null,
                max_value: null,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 75,
                stage: 96,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-29T04:00:09.545039Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "yes",
            notification: false,
            email: null,
            order: 1,
            user: null,
            group: null,
            form: 75,
            stage: 96,
            audit_info: null,
            audit_group: null,
            question: 304,
            follow_up: null,
          },
          {
            id: 35,
            logic_questions: [
              {
                id: 306,
                options: [],
                created_at: "2025-07-29T04:00:10.193156Z",
                updated_at: null,
                question_uuid: "sub-q1753760987455-vfgtp8",
                question:
                  "why its taking to long to resolve please provide the details ?",
                description: null,
                critical: false,
                formula: null,
                question_type: "title_and_description",
                question_sub_type: null,
                question_hint: null,
                order: 1,
                is_required: false,
                require_live: false,
                number_of_file_allowed: null,
                min_value: null,
                max_value: null,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 75,
                stage: 96,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-29T04:00:10.062832Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "no",
            notification: false,
            email: null,
            order: 1,
            user: null,
            group: null,
            form: 75,
            stage: 96,
            audit_info: null,
            audit_group: null,
            question: 304,
            follow_up: null,
          },
          {
            id: 36,
            logic_questions: [
              {
                id: 307,
                options: [],
                created_at: "2025-07-29T04:00:10.711765Z",
                updated_at: null,
                question_uuid: "sub-q1753761024407-8n9hvm",
                question: "upload the video of the work your doing",
                description: null,
                critical: false,
                formula: null,
                question_type: "upload_file",
                question_sub_type: null,
                question_hint: null,
                order: 1,
                is_required: false,
                require_live: false,
                number_of_file_allowed: null,
                min_value: null,
                max_value: null,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 75,
                stage: 96,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-29T04:00:10.581045Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "ongoing",
            notification: false,
            email: null,
            order: 1,
            user: null,
            group: null,
            form: 75,
            stage: 96,
            audit_info: null,
            audit_group: null,
            question: 304,
            follow_up: null,
          },
        ],
      },
    ],
    created_at: "2025-07-29T04:00:07.379812Z",
    updated_at: null,
    name: "dropdown logic testing",
    order: 2,
    is_completed: false,
    completed_on: null,
    form: 75,
    completed_by: null,
  },
  {
    id: 97,
    questions: [
      {
        id: 308,
        options: [
          {
            id: 120,
            created_at: "2025-07-29T04:00:12.341985Z",
            updated_at: null,
            option: "start",
            score: 0,
            failed: false,
            order: 1,
            question: 308,
            stage: 97,
            audit_info: null,
            audit_group: null,
            form: 75,
          },
          {
            id: 121,
            created_at: "2025-07-29T04:00:12.795551Z",
            updated_at: null,
            option: "end",
            score: 0,
            failed: false,
            order: 2,
            question: 308,
            stage: 97,
            audit_info: null,
            audit_group: null,
            form: 75,
          },
        ],
        question_uuid: "q1753761084118-soi8zt",
        question: "please provide a point from the scale",
        description: null,
        critical: false,
        formula: null,
        question_type: "linear_scale",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: false,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 75,
        stage: 97,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [
          {
            id: 37,
            logic_questions: [
              {
                id: 309,
                options: [],
                created_at: "2025-07-29T04:00:13.122742Z",
                updated_at: null,
                question_uuid: "sub-q1753761199979-skenw7",
                question: "please give us review about our service",
                description: null,
                critical: false,
                formula: null,
                question_type: "title_and_description",
                question_sub_type: null,
                question_hint: null,
                order: 1,
                is_required: false,
                require_live: false,
                number_of_file_allowed: null,
                min_value: null,
                max_value: null,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 75,
                stage: 97,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-29T04:00:12.992101Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "0",
            notification: false,
            email: null,
            order: 1,
            user: null,
            group: null,
            form: 75,
            stage: 97,
            audit_info: null,
            audit_group: null,
            question: 308,
            follow_up: null,
          },
        ],
      },
    ],
    created_at: "2025-07-29T04:00:11.492411Z",
    updated_at: null,
    name: "Linear Scale Logic Testing",
    order: 3,
    is_completed: false,
    completed_on: null,
    form: 75,
    completed_by: null,
  },
  {
    id: 98,
    questions: [
      {
        id: 310,
        options: [],
        question_uuid: "q1753761313760-mi9qyv",
        question: "var1",
        description: null,
        critical: false,
        formula: null,
        question_type: "short_answer",
        question_sub_type: "number",
        question_hint: null,
        order: 1,
        is_required: false,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 75,
        stage: 98,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 311,
        options: [],
        question_uuid: "q1753761364071-1kpb4b",
        question: "var2",
        description: null,
        critical: false,
        formula: null,
        question_type: "short_answer",
        question_sub_type: "number",
        question_hint: null,
        order: 2,
        is_required: false,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 75,
        stage: 98,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 312,
        options: [],
        question_uuid: "q1753761418174-ac9nc3",
        question: "please answer this question",
        description: null,
        critical: false,
        formula: "SUM(#var1,#var2)*80",
        question_type: "formula",
        question_sub_type: null,
        question_hint: null,
        order: 3,
        is_required: false,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 75,
        stage: 98,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-29T04:00:13.836780Z",
    updated_at: null,
    name: "formula testing",
    order: 4,
    is_completed: false,
    completed_on: null,
    form: 75,
    completed_by: null,
  },
];
