# Generated by Django 5.2.2 on 2026-07-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0002_initial'),
        ('task', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='follow_task_sub_question',
            field=models.ForeignKey(blank=True, db_column='follow_task_sub_question_id', help_text='Sub-question that triggered the follow-up task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_sub_questions', to='form.question'),
        ),
        migrations.AddField(
            model_name='task',
            name='followup_task_form_id',
            field=models.ForeignKey(blank=True, db_column='followup_task_form_id', help_text='Follow-up task assigned form ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_task_forms', to='form.form'),
        ),
        migrations.AddField(
            model_name='task',
            name='form',
            field=models.ForeignKey(blank=True, db_column='form_id', help_text='Main form ID (null for follow-up tasks)', null=True, on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='assigned_group',
            field=models.ForeignKey(blank=True, db_column='assigned_group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_groups', to='user.groups'),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='assigned_leader',
            field=models.ForeignKey(blank=True, db_column='assigned_leader_id', help_text='Location leader assigned to the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='assigned_user',
            field=models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='task.task'),
        ),
        migrations.AddField(
            model_name='taskauditlog',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_task_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskauditlog',
            name='action_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_task_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskauditlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='task.task'),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='assignee_group',
            field=models.ForeignKey(blank=True, db_column='assignee_group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_tracking_groups', to='user.groups'),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='assignee_user',
            field=models.ForeignKey(db_column='assignee_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_tracking_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='task.task'),
        ),
    ]
