# Generated by Django 5.2.2 on 2026-07-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='form_submission',
            field=models.ForeignKey(blank=True, db_column='form_submission_id', help_text='The form submission that triggered this followup task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='form.formsubmision'),
        ),
    ]
