# Generated by Django 5.2.2 on 2026-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_add_form_submission_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_bulk_imported',
            field=models.BooleanField(db_index=True, default=False, help_text='True if task was created via bulk import, False if from normal app flow'),
        ),
    ]
