# Generated by Django 5.2.2 on 2026-07-09 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0002_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('leader', 'Location Leader')], max_length=30)),
                ('planner_name', models.CharField(help_text='Name of the planner from bulk upload', max_length=255)),
                ('planner_shared_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(help_text='Start date for the planner')),
                ('end_date', models.DateTimeField(help_text='End date for the planner')),
                ('description', models.TextField(blank=True, help_text='Description of the planner', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the user has completed this planner')),
                ('completed_on', models.DateTimeField(blank=True, help_text='When the planner was completed', null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_planners', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planner_assignments', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_assignments', to='form.form')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_assignments', to='user.groups')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_planner_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_assignments', to='user.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('followup_tasks_created', models.BooleanField(default=False, help_text='Whether follow-up tasks have been created from this submission')),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_submissions', to='form.formsubmision')),
                ('planner_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='planner.plannerassignment')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='plannerassignment',
            index=models.Index(fields=['form'], name='planner_pla_form_id_b1a6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerassignment',
            index=models.Index(fields=['user'], name='planner_pla_user_id_1092b9_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerassignment',
            index=models.Index(fields=['group'], name='planner_pla_group_i_a0630f_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerassignment',
            index=models.Index(fields=['leader'], name='planner_pla_leader__9fbe73_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerassignment',
            index=models.Index(fields=['organization'], name='planner_pla_organiz_223f09_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerassignment',
            index=models.Index(fields=['is_completed'], name='planner_pla_is_comp_a7ae97_idx'),
        ),
        migrations.AddIndex(
            model_name='plannersubmission',
            index=models.Index(fields=['planner_assignment'], name='planner_pla_planner_814ede_idx'),
        ),
        migrations.AddIndex(
            model_name='plannersubmission',
            index=models.Index(fields=['form_submission'], name='planner_pla_form_su_c5f612_idx'),
        ),
        migrations.AddIndex(
            model_name='plannersubmission',
            index=models.Index(fields=['submitted_by'], name='planner_pla_submitt_0778d2_idx'),
        ),
        migrations.AddIndex(
            model_name='plannersubmission',
            index=models.Index(fields=['followup_tasks_created'], name='planner_pla_followu_509f20_idx'),
        ),
    ]
