# Generated by Django 5.2.2 on 2026-07-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerassignment',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_planners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='started_on',
            field=models.DateTimeField(blank=True, help_text='When the user started the planner', null=True),
        ),
    ]
