# Generated by Django 5.2.2 on 2026-07-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_plannerassignment_started_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerassignment',
            name='non_completion_reason',
            field=models.TextField(blank=True, help_text='Reason provided when the planner is not completed by the due date', null=True),
        ),
    ]
