# Generated by Django 5.2.2 on 2026-07-10 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_add_non_completion_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerassignment',
            name='extended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_planners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='extended_due_date',
            field=models.DateTimeField(blank=True, help_text='Extended due date set by admin after reviewing non-completion reason', null=True),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='extended_on',
            field=models.DateTimeField(blank=True, help_text='When the due date was extended', null=True),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='extension_note',
            field=models.TextField(blank=True, help_text='Note from admin to user when extending the due date', null=True),
        ),
    ]
