# Generated by Django 5.2.2 on 2026-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_add_extension_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerassignment',
            name='reason_status',
            field=models.CharField(default='pending', help_text='Status of the non-completion reason: pending, approved, or rejected', max_length=20),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text="Admin's feedback when rejecting the non-completion reason, sent back to user for a new reason", null=True),
        ),
    ]
