# Generated by Django 5.2.2 on 2026-07-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_add_reason_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerassignment',
            name='rejection_answers',
            field=models.JSONField(blank=True, default=list, help_text="User's answers to the rejection questions"),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='rejection_questions',
            field=models.JSONField(blank=True, default=list, help_text='List of questions created by admin when rejecting, for user to answer'),
        ),
    ]
