# Generated by Django 5.2.2 on 2026-07-10 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_add_rejection_questions_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerReasonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved')], help_text='What happened in this cycle', max_length=20)),
                ('non_completion_reason', models.TextField(blank=True, help_text="User's reason at this point", null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text="Admin's rejection feedback", null=True)),
                ('rejection_questions', models.JSONField(blank=True, default=list, help_text='Questions admin asked')),
                ('rejection_answers', models.JSONField(blank=True, default=list, help_text="User's answers to questions")),
                ('extended_due_date', models.DateTimeField(blank=True, help_text='Extended due date if approved', null=True)),
                ('extension_note', models.TextField(blank=True, help_text="Admin's note if approved", null=True)),
                ('acted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('cycle_number', models.IntegerField(default=1, help_text='Which cycle of submit->review this represents')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_reason_actions', to=settings.AUTH_USER_MODEL)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_history', to='planner.plannerassignment')),
            ],
            options={
                'ordering': ['acted_on'],
                'indexes': [models.Index(fields=['planner'], name='planner_pla_planner_86dc43_idx'), models.Index(fields=['action'], name='planner_pla_action_1807fd_idx')],
            },
        ),
    ]
