# Generated by Django 5.2.2 on 2026-07-11 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
        ('planner', '0007_add_planner_reason_history'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerassignment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location associated with this planner order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_assignments', to='user.locations'),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated Order ID (e.g., VB000000001)', max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plannerassignment',
            name='planner_name',
            field=models.CharField(help_text='Name of the planner from bulk upload / Order Type', max_length=255),
        ),
        migrations.AddIndex(
            model_name='plannerassignment',
            index=models.Index(fields=['order_id'], name='planner_pla_order_i_10d339_idx'),
        ),
    ]
