# Generated by Django 5.2.2 on 2026-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_plannerassignment_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannerassignment',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated Order ID (e.g., VB000000001)', max_length=11, null=True),
        ),
    ]
