# Generated by Django 5.2.2 on 2026-07-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_plannerassignment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerassignment',
            name='early_notification_days',
            field=models.PositiveIntegerField(default=0, help_text='Days before start_date to show the planner to users on mobile (e.g., 3)'),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='parent_planner',
            field=models.ForeignKey(blank=True, help_text='Original planner this was repeated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeated_instances', to='planner.plannerassignment'),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='repeat_enabled',
            field=models.BooleanField(default=False, help_text='Whether this planner should auto-repeat'),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='repeat_generation_date',
            field=models.DateTimeField(blank=True, help_text='When the next repeated instance should be generated', null=True),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='repeat_interval_days',
            field=models.PositiveIntegerField(default=0, help_text='Interval in days before creating the next repeated planner (e.g., 50, 100)'),
        ),
    ]
