# Generated by Django 5.2.2 on 2026-07-16 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_add_repeat_planner_fields'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Folder name', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='#6366F1', help_text='Hex color for folder badge', max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planner_folders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_folders', to='user.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder this planner belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planners', to='planner.plannerfolder'),
        ),
        migrations.AddIndex(
            model_name='plannerfolder',
            index=models.Index(fields=['organization'], name='planner_pla_organiz_137f9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plannerfolder',
            unique_together={('name', 'organization')},
        ),
    ]
