# Generated by Django 5.2.2 on 2026-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_add_planner_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannerfolder',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='plannerfolder',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for folder (lower = higher up)'),
        ),
    ]
