# Generated by Django 5.2.2 on 2026-07-28 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_add_collaborative_audit_delegation'),
        ('planner', '0012_add_folder_order'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerassignment',
            name='collaborative_enabled',
            field=models.BooleanField(default=False, help_text='Whether this planner supports collaborative group delegation (audit forms via planner only)'),
        ),
        migrations.AddField(
            model_name='plannerassignment',
            name='team_leader',
            field=models.ForeignKey(blank=True, help_text='The user who can delegate audit groups to team members', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader_planners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CollaborativeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('completed', 'Completed')], default='draft', help_text='Current lifecycle status of the collaborative submission', max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, help_text='When the Team Leader started delegation', null=True)),
                ('completed_on', models.DateTimeField(blank=True, help_text='When the Team Leader signed off', null=True)),
                ('form_submission', models.ForeignKey(blank=True, help_text='The shared FormSubmision that all group answers attach to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_submissions', to='form.formsubmision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_submissions', to='user.organization')),
                ('planner_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_submissions', to='planner.plannerassignment')),
                ('team_leader', models.ForeignKey(blank=True, help_text='The user assigned as Team Leader who delegates groups', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_collaborative_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_order', models.PositiveIntegerField(default=1, help_text='Order of the group within the form')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='unassigned', max_length=30)),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
                ('reviewed_on', models.DateTimeField(blank=True, help_text='When Team Leader approved this group', null=True)),
                ('rejection_comment', models.TextField(blank=True, help_text="Team Leader's comment when rejecting a group", null=True)),
                ('assigned_question_uuids', models.JSONField(blank=True, default=list, help_text='List of question UUIDs assigned to a specific user (for question-level split). Empty means all questions in the group.')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Team Leader who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_groups', to=settings.AUTH_USER_MODEL)),
                ('assigned_users', models.ManyToManyField(help_text='Users assigned to fill this group', related_name='assigned_group_delegations', to=settings.AUTH_USER_MODEL)),
                ('audit_group', models.ForeignKey(blank=True, help_text='The audit group being delegated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='form.auditgroup')),
                ('collaborative_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_delegations', to='planner.collaborativesubmission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_delegations', to='user.organization')),
                ('submitted_by', models.ForeignKey(blank=True, help_text="User who submitted this group's answers", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_group_delegations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='collaborativesubmission',
            index=models.Index(fields=['planner_assignment'], name='planner_col_planner_de1f82_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativesubmission',
            index=models.Index(fields=['form_submission'], name='planner_col_form_su_15a2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativesubmission',
            index=models.Index(fields=['team_leader'], name='planner_col_team_le_52188f_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativesubmission',
            index=models.Index(fields=['status'], name='planner_col_status_c07a19_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativesubmission',
            index=models.Index(fields=['organization'], name='planner_col_organiz_b229c4_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdelegation',
            index=models.Index(fields=['collaborative_submission'], name='planner_gro_collabo_e4c14b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdelegation',
            index=models.Index(fields=['audit_group'], name='planner_gro_audit_g_4bd4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdelegation',
            index=models.Index(fields=['status'], name='planner_gro_status_bcf748_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdelegation',
            index=models.Index(fields=['organization'], name='planner_gro_organiz_83f60b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupdelegation',
            unique_together={('collaborative_submission', 'audit_group')},
        ),
    ]
