# Generated by Django 5.2.2 on 2026-07-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_add_collaborative_audit_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativesubmission',
            name='participant_groups',
            field=models.JSONField(blank=True, default=list, help_text='List of group IDs selected as participants during planner creation'),
        ),
        migrations.AddField(
            model_name='collaborativesubmission',
            name='participant_users',
            field=models.JSONField(blank=True, default=list, help_text='List of user IDs selected as participants during planner creation'),
        ),
    ]
