# Generated by Django 5.2.2 on 2026-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_add_collaborative_participant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdelegation',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='unassigned', max_length=30),
        ),
    ]
