# Generated by Django 5.2.2 on 2026-08-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_add_group_delegation_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdelegation',
            options={'ordering': ['group_order']},
        ),
    ]
