# Generated by Django 5.2.2 on 2026-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_seed_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermisions',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('announcements', 'Announcements'), ('forms', 'Forms'), ('tasks', 'Tasks'), ('polls', 'Polls'), ('learning_training', 'Learning & Training'), ('planner', 'Planner'), ('attendance', 'Attendance'), ('guides', 'Guides'), ('administration', 'Administration')], default='dashboard', max_length=20),
        ),
    ]
