from django.urls import path
from .views import (
    PlannerBulkUploadView,
    PlannerShareView,
    PlannerListView,
    PlannerCompleteView,
    PlannerAllView,
    PlannerStartView,
    PlannerUpdateView,
    PlannerDeleteView,
    PlannerBulkDeleteView,
    PlannerAssigneesView,
    PlannerNonCompletionReasonView,
    PlannerExtendDueDateView,
    PlannerRejectReasonView,
    PlannerDownloadTemplateView,
    PlannerFolderListView,
    PlannerFolderDetailView,
    PlannerFolderReorderView,
    PlannerFolderStatsView,
    MovePlannerToFolderView,
    CollaborativeStartView,
    CollaborativeDetailView,
    CollaborativeDelegateView,
    CollaborativeSubmitGroupView,
    CollaborativeReviewView,
    CollaborativeCompleteView,
    CollaborativeMyGroupsView,
    CollaborativeOrgUsersView,
    CollaborativePollAnswersView,
    CollaborativeAutoSaveView,
    CollaborativeChangeLeaderView,
    CollaborativeOptionStatsView,
)

urlpatterns = [
    path('bulk-import/', PlannerBulkUploadView.as_view(), name='planner-bulk-import'),
    path('share/', PlannerShareView.as_view(), name='planner-share'),
    path('my-planners/', PlannerListView.as_view(), name='my-planners'),
    path('all-planners/', PlannerAllView.as_view(), name='all-planners'),
    path('<int:planner_id>/start/', PlannerStartView.as_view(), name='planner-start'),
    path('<int:planner_id>/update/', PlannerUpdateView.as_view(), name='planner-update'),
    path('<int:planner_id>/delete/', PlannerDeleteView.as_view(), name='planner-delete'),
    path('<int:planner_id>/assignees/', PlannerAssigneesView.as_view(), name='planner-assignees'),
    path('<int:planner_id>/non-completion-reason/', PlannerNonCompletionReasonView.as_view(), name='planner-non-completion-reason'),
    path('<int:planner_id>/extend-due-date/', PlannerExtendDueDateView.as_view(), name='planner-extend-due-date'),
    path('<int:planner_id>/reject-reason/', PlannerRejectReasonView.as_view(), name='planner-reject-reason'),
    path('bulk-delete/', PlannerBulkDeleteView.as_view(), name='planner-bulk-delete'),
    path('complete/', PlannerCompleteView.as_view(), name='planner-complete'),
    path('download-template/', PlannerDownloadTemplateView.as_view(), name='planner-download-template'),
    path('folders/', PlannerFolderListView.as_view(), name='planner-folders'),
    path('folders/reorder/', PlannerFolderReorderView.as_view(), name='planner-folder-reorder'),
    path('folders/<int:folder_id>/', PlannerFolderDetailView.as_view(), name='planner-folder-detail'),
    path('folder-stats/', PlannerFolderStatsView.as_view(), name='planner-folder-stats'),
    path('move-to-folder/', MovePlannerToFolderView.as_view(), name='planner-move-to-folder'),
    # Collaborative audit delegation endpoints
    path('collaborative/my-groups/', CollaborativeMyGroupsView.as_view(), name='collaborative-my-groups'),
    path('<int:planner_id>/collaborative/', CollaborativeDetailView.as_view(), name='collaborative-detail'),
    path('<int:planner_id>/collaborative/start/', CollaborativeStartView.as_view(), name='collaborative-start'),
    path('<int:planner_id>/collaborative/delegate/', CollaborativeDelegateView.as_view(), name='collaborative-delegate'),
    path('<int:planner_id>/collaborative/submit-group/', CollaborativeSubmitGroupView.as_view(), name='collaborative-submit-group'),
    path('<int:planner_id>/collaborative/review/', CollaborativeReviewView.as_view(), name='collaborative-review'),
    path('<int:planner_id>/collaborative/complete/', CollaborativeCompleteView.as_view(), name='collaborative-complete'),
    path('<int:planner_id>/collaborative/users/', CollaborativeOrgUsersView.as_view(), name='collaborative-users'),
    path('<int:planner_id>/collaborative/poll-answers/', CollaborativePollAnswersView.as_view(), name='collaborative-poll-answers'),
    path('<int:planner_id>/collaborative/auto-save/', CollaborativeAutoSaveView.as_view(), name='collaborative-auto-save'),
    path('<int:planner_id>/collaborative/change-leader/', CollaborativeChangeLeaderView.as_view(), name='collaborative-change-leader'),
    path('<int:planner_id>/collaborative/option-stats/', CollaborativeOptionStatsView.as_view(), name='collaborative-option-stats'),
]
